title = "Traffic Fines for Bikes"

[changes]
	[changes.20130314]
	author = "sondh"
	reason = "create bike.toml"

[fines]
	[fines.test]
	name                  = "Test Fine"
	description           = "Some description text"
	fine                  = "100000-200000"
	fine_source           = "http://domain.com/source"
	fine_big_city         = ""
	fine_big_city_source  = "http://domain.com/source"
	license_days          = 0
	license_days_source   = "http://domain.com/source"
	vehicle_days          = 0
	vehicle_days_source   = "http://domain.com/source"
	updated_ymd           = 20130318
	active_since_ymd      = 20130314
	active_now            = 0

	[fines.71_2012_ndcp_1_8_33_3_c]
	name                  = "Tự ý thay đổi khung, máy, hình dáng, kích thước của xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/1/8-33/3/c"
	updated_ymd           = 20130318
	active_since_ymd      = 20130314
	active_now            = 1
	
	[fines.43_2010_ndcp_20_1_a]
	name                  = "Không có còi; đèn soi biển số; đèn báo hãm; gương chiếu hậu bên trái người điều khiển hoặc có nhưng không có tác dụng"
	description           = "Phạt tiền từ 80.000 đồng đến 100.000 đồng"
	fine                  = "80000-100000"
	fine_source           = "2010/20/1/a"
	updated_ymd           = 20130318
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_1_a]
	name                  = "Tụ tập để cổ vũ, kích động hành vi điều khiển xe chạy quá tốc độ quy định, lạng lách, đánh võng, đuổi nhau trên đường hoặc đua xe trái phép;"
	description           = "Phạt tiền từ 1.000.000 đồng đến 2.000.000 đồng "
	fine                  = "1000000-2000000"
	fine_source           = "2012/1/10-37/1/a"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_1_b]
	name                  = "Đua xe đạp, đua xe đạp máy, đua xe xích lô, đua xe súc vật kéo, cưỡi súc vật chạy đua trái phép trên đường giao thông."
	description           = "Phạt tiền từ 1.000.000 đồng đến 2.000.000 đồng "
	fine                  = "1000000-2000000"
	fine_source           = "2012/1/10-37/1/b"
	vehicle_days	      = 9999
	vehicle_days_source   = "2012/1/10-37/1/b"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_2]
	name                  = "Cổ vũ, kích động đua xe trái phép mà cản trở hoặc chống người thi hành công vụ."
	description           = "Phạt tiền từ 4.000.000 đồng đến 6.000.000 đồng "
	fine                  = "4000000-6000000"
	fine_source           = "2012/1/10-37/2"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_4]
	name                  = "Đua xe ô tô trái phép"
	description           = "Phạt tiền từ 20.000.000 đồng đến 30.000.000 đồng"
	fine                  = "10000000-20000000"
	fine_source           = "2012/1/10-37/4"
	license_days          = 9999
	license_days_source   = "2012/1/10-37/4"
	vehicle_days 	      = 9999
	vehicle_days_source   = "2012/1/10-37/4"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_5_a]
	name                  = "Đua xe ô tô, xe mô tô, xe gắn máy, xe máy điện, xe đạp máy mà chống người thi hành công vụ;"
	description           = "Phạt tiền từ 30.000.000 đồng đến 40.000.000 đồng"
	fine                  = "30000000-40000000"
	fine_source           = "2012/1/10-37/5/a"
	license_days          = 9999
	license_days_source   = "2012/1/10-37/5/a"
	vehicle_days 	      = 9999
	vehicle_days_source   = "2012/1/10-37/5/a"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.71_2012_ndcp_1_10_37_5_b]
	name                  = "Tổ chức đua xe trái phép."
	description           = "Phạt tiền từ 30.000.000 đồng đến 40.000.000 đồng"
	fine                  = "30000000-40000000"
	fine_source           = "2012/1/10-37/5/b"
	updated_ymd           = 20130318
	active_since_ymd      = 20130315
	active_now            = 1
