title = "Traffic Fines for Bikes"

[changes]
	[changes.20130314]
	author = "sondh"
	reason = "create bike.toml"

[fines]
	[fines.test]
	name                  = "Test Fine"
	description           = "Some description text"
	fine                  = "100000-200000"
	fine_source           = "http://domain.com/source"
	fine_big_city         = ""
	fine_big_city_source  = "http://domain.com/source"
	license_days          = 0
	license_days_source   = "http://domain.com/source"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 0

	[fines.71_2012_ndcp_8_3_c]
	name                  = "Tự ý thay đổi khung, máy, hình dáng, kích thước của xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "http://giaothongvn.com/nghi-dinh-71/Diem-c/Khoan-3/Dieu-8/"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1
	
	[fines.34_2010_ndcp_20_1_a]
	name                  = "Không có còi; đèn soi biển số; đèn báo hãm; gương chiếu hậu bên trái người điều khiển hoặc có nhưng không có tác dụng"
	description           = "Phạt tiền từ 80.000 đồng đến 100.000 đồng"
	fine                  = "80000-100000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.34_2010_ndcp_20_1_b]
	name                  = "Gắn biển số không đúng quy định; biển số không rõ chữ, số; biển số bị bẻ cong, bị che lấp, bị hỏng"
	description           = "Phạt tiền từ 80.000 đồng đến 100.000 đồng"
	fine                  = "80000-100000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_1_c]
	name                  = "Điều khiển xe không có đèn tín hiệu hoặc có nhưng không có tác dụng"
	description           = "Phạt tiền từ 80.000 đồng đến 100.000 đồng"
	fine                  = "80000-100000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_2_a]
	name                  = "Sử dụng còi không đúng quy chuẩn kỹ thuật cho từng loại xe"
	description           = "Phạt tiền từ 100.000 đồng đến 200.000 đồng, tịch thu còi"
	fine                  = "100000-200000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_2_b]
	name                  = "Không có bộ phận giảm thanh, giảm khói hoặc có nhưng không bảo đảm quy chuẩn môi trường về khí thải, tiếng ồn"
	description           = "Phạt tiền từ 100.000 đồng đến 200.000 đồng"
	fine                  = "100000-200000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_2_c]
	name                  = "Không có đèn chiếu sáng gần, xa hoặc có nhưng không có tác dụng"
	description           = "Phạt tiền từ 100.000 đồng đến 200.000 đồng"
	fine                  = "100000-200000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_2_d]
	name                  = "Không có hệ thống hãm hoặc có nhưng không bảo đảm tiêu chuẩn kỹ thuật"
	description           = "Phạt tiền từ 100.000 đồng đến 200.000 đồng"
	fine                  = "100000-200000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_3_a]
	name                  = "Không có Giấy đăng ký xe theo quy định"
	description           = "Phạt tiền từ 300.000 đồng đến 500.000 đồng"
	fine                  = "300000-500000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1


	[fines.34_2010_ndcp_20_3_b]
	name                  = "Sử dụng Giấy đăng ký xe đã bị tẩy xóa; sử dụng Giấy đăng ký xe không đúng số khung, số máy của xe hoặc không do cơ quan có thẩm quyền cấp"
	description           = "Phạt tiền từ 300.000 đồng đến 500.000 đồng, tịch thu Giấy đăng ký, biển số không đúng quy định"
	fine                  = "300000-500000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_3_c]
	name                  = "Không gắn biển số (nếu có quy định phải gắn biển số); gắn biển số không đúng với số hoặc ký hiệu trong Giấy đăng ký; biển số không do cơ quan có thẩm quyền cấp"
	description           = "Phạt tiền từ 300.000 đồng đến 500.000 đồng, tịch thu Giấy đăng ký, biển số không đúng quy định"
	fine                  = "300000-500000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_4_a]
	name                  = "Xe đăng ký tạm hoạt động quá phạm vi, thời hạn cho phép"
	description           = "Phạt tiền từ 800.000 đồng đến 1.000.000 đồng"
	fine                  = "800000-1000000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 30
	license_days_source   = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1

	[fines.34_2010_ndcp_20_4_b]
	name                  = "Điều khiển xe tự sản xuất, lắp ráp"
	description           = "Phạt tiền từ 800.000 đồng đến 1.000.000 đồng"
	fine                  = "800000-1000000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 60
	license_days_source   = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
        vehicle_days          = 60
        vehicle_days_source   = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1


	[fines.34_2010_ndcp_31_1]
	name                  = "Điều khiển xe mô tô, xe gắn máy, xe thô sơ chở hành khách, hàng hóa không có biển hiệu hoặc trang phục theo quy định"
	description           = "Cảnh cáo hoặc phạt tiền từ 40.000 đồng đến 60.000 đồng "
	fine                  = "40000-60000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = ""
	license_days_source   = ""
        vehicle_days          = ""
        vehicle_days_source   = ""
	updated_ymd           = 20130315
	active_since_ymd      = 20130315
	active_now            = 1



